### PR TITLE
upgrade prettier

### PR DESCRIPTION
**Pull request by mccullochk**
This was using a outdated version of prettier which has started creating version conflicts on new projects.

Updated the version number to indicate the significant change.

### CODE REVIEW

**Review by calebissharp — APPROVED** [review]
Thanks!

**Comment by mccullochk** [comment]
@calebissharp, how do we get this to propagate to npm?

**Comment by calebissharp** [comment]
@mccullochk `npm publish` IIRC. You probably also want to create a tag and release in GitHub.

**Comment by mccullochk** [comment]
@calebissharp, I don't think I have access to our NPM registry. Do you?

**Comment by calebissharp** [comment]
@mccullochk Yep, published.

**Comment by mccullochk** [comment]
Thanks @calebissharp !

**Pull request merged**
